services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: TesloDB
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data